-- Primera practica
CREATE TABLE DANCE(ID_DANCE INTEGER, NOMBRE VARCHAR2(40), EDAD INTEGER);

-- ACTIVAMOS MODO DE CONSOLA
SET SERVEROUTPUT ON;

--BLOQUE PL SQL
DECLARE
EDAD INTEGER;
YEARS INTEGER;
BEGIN
YEARS:=42;
EDAD:=YEARS*365;

DBMS_OUTPUT.PUT_LINE('tU EDAD EN DIAS ES:'||EDAD);
END;
/
--CREAR UN BLOQUE SQL QUE GENERE 200,000 REGISRO EN SECUENCIA ASCENDENTE EN LA TABLA DANCE
BEGIN

  FOR I IN 1..200000 LOOP
    INSERT INTO DANCE VALUES(I,'MIRIAM',20);
    
  END LOOP;
END;
/
--hacemos un select 
  SELECT * FROM DANCE;
  
--SISTEMA DE PELICULAS LA DE LA SALA SERA LA TAREA
  CREATE TABLE PELICULA(ID_PELICULA INTEGER,
               TITULO   VARCHAR(120),
               SINOPSIS VARCHAR(300),
               CLASIFICACION VARCHAR(5),
               CONSTRAINT PK_ID_PELICULA PRIMARY KEY(ID_PELICULA)
               );
               describe PELICULA;
  CREATE TABLE HORARIO (ID_HORARIO INTEGER,
                ID_PELICULA INTEGER,
                HORARIO VARCHAR(8),
                CONSTRAINT PK_ID_HORARIO PRIMARY KEY(ID_HORARIO),
                CONSTRAINT FK1_ID_PELICULA FOREIGN KEY(ID_PELICULA) REFERENCES PELICULA(ID_PELICULA)
                );
                DESCRIBE HORARIO;
CREATE SEQUENCE SEC_PELICULA
start with 1
increment by 1
nomaxvalue;

SET SERVEROUTPUT ON;
CREATE OR REPLACE PROCEDURE HOLA_MUNDO(NOMBRE IN VARCHAR2)
AS
BEGIN
--AQUI VA LA LOGICA--
DBMS_OUTPUT.PUT_LINE('HOLA COMO ESTAS' || NOMBRE);
END;

/
--INVOCAR DESDE EL MISMO SQL EL PROCEDIMIENTO 
BEGIN 
HOLA_MUNDO(' MIRIAM');
END;

/

